netbull_translation_locale_switcher:
    path: /changeLocale/{_locale}
    defaults:
        _controller: netbull_translation.locale_switcher_controller::switchAction
        _locale: '%kernel.default_locale%'
