services:
    NetBull\TranslationBundle\Form\TranslationForm:
        arguments: [ '@form.registry', '@doctrine' ]

    NetBull\TranslationBundle\Form\EventListener\TranslationsSubscriber:
        arguments: [ '@NetBull\TranslationBundle\Form\TranslationForm', '@form.factory' ]

    NetBull\TranslationBundle\Form\Type\TranslationsType:
        tags:
            - { name: form.type, alias: netbull_translations }
        arguments: [ '@NetBull\TranslationBundle\Form\EventListener\TranslationsSubscriber', '%kernel.default_locale%', '' ]

    NetBull\TranslationBundle\Form\Type\TranslationsFieldsType:
        tags:
            - { name: form.type, alias: netbull_translationsFields }
