services:
    NetBull\TranslationBundle\Guessers\RouteParamLocaleGuesser:
        arguments: [ '@NetBull\TranslationBundle\Validator\MetaValidator' ]
        tags:
            - { name: 'locale_guesser', alias: 'route' }

    NetBull\TranslationBundle\Guessers\DomainLocaleGuesser:
        arguments: [ '@NetBull\TranslationBundle\Validator\MetaValidator', '@NetBull\TranslationBundle\Locale\LocaleMap' ]
        tags:
            - { name: 'locale_guesser', alias: 'domain' }

    NetBull\TranslationBundle\Guessers\CookieLocaleGuesser:
        arguments: [ '@NetBull\TranslationBundle\Validator\MetaValidator', '%netbull_translation.cookie.name%' ]
        tags:
            - { name: 'locale_guesser', alias: 'cookie' }

    NetBull\TranslationBundle\Guessers\SessionLocaleGuesser:
        arguments: [ '@request_stack', '@NetBull\TranslationBundle\Validator\MetaValidator', '%netbull_translation.session.variable%' ]
        tags:
            - { name: 'locale_guesser', alias: 'session' }

    NetBull\TranslationBundle\Guessers\GeoIpLocaleGuesser:
        arguments: [ '@NetBull\TranslationBundle\Validator\MetaValidator', '%netbull_translation.geoip.binary%', '%netbull_translation.geoip.default%', '@NetBull\TranslationBundle\Locale\CountryMap' ]
        tags:
            - { name: 'locale_guesser', alias: 'geoip' }

    NetBull\TranslationBundle\Guessers\LocaleGuesserManager:
        arguments: [ '%netbull_translation.guessing_order%', '@logger' ]
