services:
    NetBull\TranslationBundle\EventListener\LocaleListener:
        tags:
            - { name: kernel.event_subscriber }
        arguments: [ '@NetBull\TranslationBundle\Guessers\LocaleGuesserManager', '%kernel.default_locale%', '@?NetBull\TranslationBundle\Matcher\DefaultBestLocaleMatcher', '@logger' ]
        calls:
            - [ setEventDispatcher, [ '@event_dispatcher' ] ]
            - [ setDisableVaryHeader, [ '%netbull_translation.disable_vary_header%' ] ]
            - [ setExcludedPattern, [ '%netbull_translation.guessing_excluded_pattern%' ] ]

    NetBull\TranslationBundle\EventListener\LocaleUpdateListener:
        arguments: [ '@event_dispatcher', '@NetBull\TranslationBundle\Locale\Cookie\LocaleCookie', '@?NetBull\TranslationBundle\Locale\Session\LocaleSession', '%netbull_translation.guessing_order%', '@logger' ]
        tags:
            - { name: kernel.event_subscriber }
