services:
    NetBull\TranslationBundle\Information\AllowedLocalesProvider:
        public: true
        calls:
            - [ setAllowedLocales, [ '%netbull_translation.allowed_locales%' ] ]

    NetBull\TranslationBundle\Locale\LocaleMap:
        arguments: [ '%netbull_translation.locale_map%' ]

    NetBull\TranslationBundle\Locale\CountryMap:
        arguments: [ '%netbull_translation.geoip.country_map%' ]

    NetBull\TranslationBundle\Matcher\DefaultBestLocaleMatcher:
        arguments: [ '@NetBull\TranslationBundle\Information\AllowedLocalesProvider' ]

    NetBull\TranslationBundle\Locale\Cookie\LocaleCookie:
        arguments:
            - '%netbull_translation.cookie.name%'
            - '%netbull_translation.cookie.ttl%'
            - '%netbull_translation.cookie.path%'
            - '%netbull_translation.cookie.secure%'
            - '%netbull_translation.cookie.httpOnly%'
            - '%netbull_translation.cookie.set_on_change%'
            - '%netbull_translation.cookie.domain%'

    NetBull\TranslationBundle\Locale\Session\LocaleSession:
        arguments: [ '@request_stack', '%netbull_translation.session.variable%' ]

    NetBull\TranslationBundle\Templating\LocaleSwitchHelper:
        public: true
        arguments: [ '@twig', '%netbull_translation.switcher.template%' ]

    NetBull\TranslationBundle\Controller\LocaleController:
        public: true
        arguments:
            - '@event_dispatcher'
            - '@NetBull\TranslationBundle\Validator\MetaValidator'
            - '@router'
            - '%netbull_translation.switcher.use_referrer%'
            - '%netbull_translation.switcher.redirect_to_route%'
            - '%netbull_translation.switcher.redirect_status_code%'
