netbull_translation_locale_switcher:
    path: /changeLocale/{newLocale}
    controller: netbull_translation.locale_switcher_controller::switchAction
    defaults:
        newLocale: '%kernel.default_locale%'
    requirements:
        newLocale: '\w{2}'

