services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    NetBull\TranslationBundle\:
        resource: '../../**/*Listener.php'

    NetBull\TranslationBundle\Twig\TranslationExtension:
        arguments: [ '@service_container', '@request_stack' ]
        tags:
            - { name: twig.extension }
