services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    NetBull\TranslationBundle\:
        resource: '../../**/*Listener.php'

    netbull_translation.twig.extension:
        class: NetBull\TranslationBundle\Twig\TranslationExtension
        arguments: [ '@service_container', '@request_stack' ]
        tags:
            - { name: twig.extension }
