services:
  netbull_translation.validator.locale:
    class: NetBull\TranslationBundle\Validator\LocaleValidator
    tags:
      - { name: validator.constraint_validator, alias: netbull_translation.validator.locale }
    arguments:
      - '%netbull_translation.intl_extension_installed%'
      - '%netbull_translation.intl_extension_fallback.iso3166%'
      - '%netbull_translation.intl_extension_fallback.iso639%'
      - '%netbull_translation.intl_extension_fallback.script%'

  netbull_translation.validator.locale_allowed:
    class: NetBull\TranslationBundle\Validator\LocaleAllowedValidator
    tags:
      - { name: validator.constraint_validator, alias: netbull_translation.validator.locale_allowed }
    arguments: ['@netbull_translation.allowed_locales_provider']

  netbull_translation.validator.meta:
    class: NetBull\TranslationBundle\Validator\MetaValidator
    arguments: ['@validator']
